"""Glyph coverage of the production pixel faces (content-system roadmap M48).

Reads every SAI Pixel face in public/fonts/ and writes
src/content-engine/i18n/font-coverage.json: the code points each face maps,
as ranges, and `common`, the ranges every proportional face maps. The i18n
gate refuses translated text with a character outside `common`, because the
browser would draw it with a fallback font: anti-aliased, off the pixel grid,
and outside the palette closure the pixel gate proves.

The file records each face's SHA-256, so site:doctor can tell when the faces
were rebuilt without regenerating the coverage.

Usage: npm run fonts:coverage
"""
import hashlib
import json
import sys
from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
FONTS = ROOT / "public" / "fonts"
OUT = ROOT / "src" / "content-engine" / "i18n" / "font-coverage.json"


def ranges(points):
    out = []
    for cp in sorted(points):
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def main():
    manifest = json.loads((FONTS / "manifest.json").read_text(encoding="utf-8"))
    faces = []
    common = None
    for face in manifest["faces"]:
        path = FONTS / face["file"]
        cmap = set(TTFont(path).getBestCmap().keys())
        faces.append({
            "file": face["file"],
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "glyphs": len(cmap),
            "ranges": ranges(cmap),
        })
        # The monospace face only draws code, which stays canonical ASCII.
        if "mono" not in face["file"]:
            common = cmap if common is None else common & cmap
    doc = {
        "note": "Generated by scripts/fonts/coverage.py (npm run fonts:coverage) from public/fonts. `common` is what every proportional face can draw; translated text must stay inside it.",
        "generator": "scripts/fonts/coverage.py",
        "faces": faces,
        "common": ranges(common or set()),
    }
    OUT.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(faces)} faces, {sum(b - a + 1 for a, b in doc['common'])} common code points")


if __name__ == "__main__":
    sys.exit(main())
