"""Glyph coverage of the production pixel faces (content-system roadmap M48).

Reads every SAI Pixel face in public/fonts/ and writes
src/content-engine/i18n/font-coverage.json: the code points each face maps,
as ranges, and `common`, the ranges every proportional face maps. The i18n
gate refuses translated text with a character outside `common`, because the
browser would draw it with a fallback font: anti-aliased, off the pixel grid,
and outside the palette closure the pixel gate proves.

The code face has its own contract, kept separate on purpose: `mono` records
what SAI Pixel Mono 12 can draw, which source drew it, and - for the composite
face - every code point the DejaVu Sans Mono supplement had to add. Code and
literal notation are not translated prose, so folding the two together would
let a translation gate pass text the code face cannot draw.

The file records each face's SHA-256, so site:doctor can tell when the faces
were rebuilt without regenerating the coverage.

Usage: npm run fonts:coverage
"""
import hashlib
import json
import sys
from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
FONTS = ROOT / "public" / "fonts"
OUT = ROOT / "src" / "content-engine" / "i18n" / "font-coverage.json"
SOURCES = ROOT / "scripts" / "fonts" / "sources.json"


def ranges(points):
    out = []
    for cp in sorted(points):
        if out and cp == out[-1][1] + 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def main():
    manifest = json.loads((FONTS / "manifest.json").read_text(encoding="utf-8"))
    sources = json.loads(SOURCES.read_text(encoding="utf-8"))
    problems = []
    faces = []
    common = None
    mono = None
    for face in manifest["faces"]:
        path = FONTS / face["file"]
        cmap = set(TTFont(path).getBestCmap().keys())
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        faces.append({
            "file": face["file"],
            "sha256": digest,
            "glyphs": len(cmap),
            "ranges": ranges(cmap),
        })
        # The monospace face only draws code, which stays canonical ASCII plus
        # the literal notation and letters a code payload can carry. It is
        # reported under `mono`, never merged into the proportional `common`.
        if "mono" in face["file"]:
            declared = {s["role"]: s for s in face.get("sources", [])}
            primary = declared.get("primary")
            supplement = declared.get("missing-glyph supplement")
            if not primary or not supplement:
                problems.append(f"{face['file']}: manifest does not record both a primary and a supplement source")
                continue
            if primary["sha256"] != sources["code"]["sha256"]:
                problems.append(f"{face['file']}: primary source is not the approved Spleen 6x12")
            if supplement["sha256"] != sources["code"]["supplement"]["sha256"]:
                problems.append(f"{face['file']}: supplement source is not the approved DejaVu Sans Mono")
            supplemented = face.get("supplemented", [])
            absent = [cp for cp in supplemented if cp not in cmap]
            if absent:
                problems.append(
                    f"{face['file']}: {len(absent)} recorded supplement code point(s) are not in the built cmap "
                    f"({', '.join(f'U+{cp:04X}' for cp in absent[:8])})"
                )
            if face.get("primary_glyphs", 0) + len(supplemented) != len(cmap):
                problems.append(
                    f"{face['file']}: {face.get('primary_glyphs', 0)} primary + {len(supplemented)} supplement "
                    f"!= {len(cmap)} glyphs in the cmap"
                )
            mono = {
                "file": face["file"],
                "sha256": digest,
                "glyphs": len(cmap),
                "ranges": ranges(cmap),
                "primary": {"source": primary["name"], "sha256": primary["sha256"], "glyphs": face.get("primary_glyphs", 0)},
                "supplement": {
                    "source": supplement["name"],
                    "sha256": supplement["sha256"],
                    "glyphs": len(supplemented),
                    "codepoints": sorted(supplemented),
                },
            }
        else:
            common = cmap if common is None else common & cmap
    if mono is None:
        problems.append("no monospace face in public/fonts/manifest.json")
    if problems:
        for p in problems:
            print(f"  FAIL {p}")
        print(f"\nFAILED: {len(problems)} font coverage problem(s)")
        return 1
    doc = {
        "note": "Generated by scripts/fonts/coverage.py (npm run fonts:coverage) from public/fonts. `common` is what every proportional face can draw; translated text must stay inside it. `mono` is the separate code-face contract.",
        "generator": "scripts/fonts/coverage.py",
        "faces": faces,
        "common": ranges(common or set()),
        "mono": mono,
    }
    OUT.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(faces)} faces, "
        f"{sum(b - a + 1 for a, b in doc['common'])} common code points, "
        f"mono {mono['glyphs']} glyphs ({mono['primary']['glyphs']} {mono['primary']['source']} "
        f"+ {mono['supplement']['glyphs']} {mono['supplement']['source']} supplement)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
