"""
Turn the SAIPEN brand artwork in src/media/ into pixel-law website assets.

The originals are large anti-aliased PNGs (white artwork on transparency).
The site needs Class A pixel art (WINTAGE_WEB_CONTRACT §8, §23): drawn at the
exact size it is displayed, hard 1-bit edges, colour from the active palette.

So each asset is a 1-bit ALPHA MASK at its display size: the original alpha is
resampled once (Lanczos) to the target size and thresholded at 50 %. The page
paints a palette token through the mask (CSS `mask` + `background-color`), so
every mark follows all sixteen themes, carries no colour of its own and never
scales. Only the favicon has a baked colour (Golden Default borderHighlight),
because browser chrome cannot read the page's CSS variables.

Usage: npm run media:build   (python scripts/media/build_media.py)
Deterministic: same sources, same bytes.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src/media"
OUT = ROOT / "public/media"

# name -> (source file, crop box in source pixels, output width, output height)
ASSETS = {
    "saipen-wordmark-480.png": ("SAIPEN_TEXT1.png", (18, 35, 3616, 648), 480, 82),
    "saipen-wordmark-288.png": ("SAIPEN_TEXT1.png", (18, 35, 3616, 648), 288, 49),
    "saipen-emblem-96.png": ("SAIPEN_design2_alpha.png", (673, 256, 3405, 2965), 96, 96),
    "saipen-emblem-64.png": ("SAIPEN_design2_alpha.png", (673, 256, 3405, 2965), 64, 64),
    "saipen-banner-332.png": ("SAIPEN_design1.png", (251, 295, 3965, 1637), 332, 120),
}
FAVICON = ("favicon-32.png", "__SAIPEN_Alpha.png", (161, 160, 3860, 3859), 32, (0xF0, 0xD0, 0x60))


def one_bit(source: str, box: tuple[int, int, int, int], width: int, height: int) -> Image.Image:
    alpha = Image.open(SRC / source).getchannel("A").crop(box)
    alpha = alpha.resize((width, height), Image.LANCZOS)
    return alpha.point(lambda v: 255 if v >= 128 else 0)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    records = []
    for name, (source, box, width, height) in ASSETS.items():
        alpha = one_bit(source, box, width, height)
        image = Image.new("LA", (width, height), 255)
        image.putalpha(alpha)
        image.save(OUT / name, optimize=True)
        records.append({"file": name, "source": f"src/media/{source}", "source_sha256": sha(SRC / source),
                        "crop": list(box), "width": width, "height": height, "kind": "alpha mask",
                        "sha256": sha(OUT / name)})

    name, source, box, size, rgb = FAVICON
    alpha = Image.open(SRC / source).getchannel("A").crop(box).resize((size, size), Image.LANCZOS)
    icon = Image.new("RGBA", (size, size), rgb + (255,))
    icon.putalpha(alpha)
    icon.save(OUT / name, optimize=True)
    records.append({"file": name, "source": f"src/media/{source}", "source_sha256": sha(SRC / source),
                    "crop": list(box), "width": size, "height": size, "kind": "favicon, Golden Default borderHighlight",
                    "sha256": sha(OUT / name)})

    alpha_16 = Image.open(SRC / source).getchannel("A").crop(box).resize((16, 16), Image.LANCZOS)
    ico_16 = Image.new("RGBA", (16, 16), rgb + (255,))
    ico_16.putalpha(alpha_16)
    icon.save(ROOT / "public/favicon.ico", format="ICO", sizes=[(16, 16), (32, 32)], append_images=[ico_16])

    manifest = {
        "note": "SAIPEN brand marks as 1-bit pixel assets. Generated by scripts/media/build_media.py from src/media/ (SAIPEN project artwork).",
        "generator": "scripts/media/build_media.py",
        "assets": records,
        # AUDAPACK manifest closure: the marks are part of the visual evidence.
        "required": [r["file"] for r in records],
    }
    (OUT / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    for r in records:
        print(f"{r['file']:28} {r['width']}x{r['height']}  {r['kind']}")


if __name__ == "__main__":
    main()
